name: moomalpublication
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 
  dio:
  connectivity_plus:
  shared_preferences:
  intl:
  shimmer:
  lottie:
  cached_network_image:
  flutter_svg:
  cupertino_icons: 
  internet_connection_checker:
  dropdown_button2:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svgs/
    - assets/pngs/
    - assets/animation/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri/calibri-regular.ttf
        - asset: assets/fonts/calibri/calibri-bold.ttf

    - family: Gupter
      fonts:
        - asset: assets/fonts/gupter/Gupter-Regular.ttf
        - asset: assets/fonts/gupter/Gupter-Medium.ttf
        - asset: assets/fonts/gupter/Gupter-Bold.ttf

    - family: Mina
      fonts:
        - asset: assets/fonts/mina/Mina-Regular.ttf
        - asset: assets/fonts/mina/Mina-Bold.ttf

    - family: MontaguSlab
      fonts:
        - asset: assets/fonts/montagu_slab/MontaguSlab_48pt-Bold.ttf
