name: moomalpublication
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2 
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^2.7.0 
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6 
  internet_connection_checker: ^1.0.0
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.2 
  flutter_html: ^3.0.0-beta.2
  payu_checkoutpro_flutter: ^1.0.4
  crypto: ^3.0.3
  share_plus: ^7.2.1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svgs/
    - assets/pngs/
    - assets/animation/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri/calibri-regular.ttf
        - weight: 400
        - asset: assets/fonts/calibri/calibri-bold.ttf
        - weight: 700

    - family: Gupter
      fonts:
        - asset: assets/fonts/gupter/Gupter-Regular.ttf
        - weight: 400
        - asset: assets/fonts/gupter/Gupter-Medium.ttf
        - weight: 500
        - asset: assets/fonts/gupter/Gupter-Bold.ttf
        - weight: 700

    - family: Mina
      fonts:
        - asset: assets/fonts/mina/Mina-Regular.ttf
        - weight: 400
        - asset: assets/fonts/mina/Mina-Bold.ttf
        - weight: 700

    - family: MontaguSlab
      fonts:
        - asset: assets/fonts/montagu_slab/MontaguSlab_48pt-Bold.ttf
        - weight: 700
